# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/bowser-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/bowser-common/proprietary/bin/battery_log.sh:/system/bin/battery_log.sh \
    vendor/amazon/bowser-common/proprietary/bin/cond_start_ril:/system/bin/cond_start_ril \
    vendor/amazon/bowser-common/proprietary/bin/emmc_init.sh:/system/bin/emmc_init.sh \
    vendor/amazon/bowser-common/proprietary/bin/temperature_log.sh:/system/bin/temperature_log.sh \
    vendor/amazon/bowser-common/proprietary/bin/thermal_setup.sh:/system/bin/thermal_setup.sh \
    vendor/amazon/bowser-common/proprietary/etc/wifi/nvram_tate_usi.txt:system/etc/wifi/nvram_tate_usi.txt \
    vendor/amazon/bowser-common/proprietary/etc/wifi/nvram_tate_semco.txt:system/etc/wifi/nvram_tate_semco.txt \
    vendor/amazon/bowser-common/proprietary/etc/wifi/nvram_jem_semco.txt:system/etc/wifi/nvram_jem_semco.txt \
    vendor/amazon/bowser-common/proprietary/etc/wifi/nvram_jem_usi.txt:system/etc/wifi/nvram_jem_usi.txt \
    vendor/amazon/bowser-common/proprietary/etc/wifi/nvram_jem-wan_semco.txt:system/etc/wifi/nvram_jem-wan_semco.txt \
    vendor/amazon/bowser-common/proprietary/etc/wifi/nvram_jem-wan_usi.txt:system/etc/wifi/nvram_jem-wan_usi.txt \
    vendor/amazon/bowser-common/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \
    vendor/amazon/bowser-common/proprietary/lib/libddp_omx.so:system/lib/libddp_omx.so \
    vendor/amazon/bowser-common/proprietary/lib/libstagefright_soft_ddpdec.so:system/lib/libstagefright_soft_ddpdec.so \
    vendor/amazon/bowser-common/proprietary/lib/soundfx/libdolbysurroundeffect.so:system/lib/soundfx/libdolbysurroundeffect.so

