# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/tate/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/tate/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/amazon/jem/proprietary/vendor/firmware/bcm2076_20mhz.hcd:system/vendor/firmware/bcm2076_20mhz.hcd \
    vendor/amazon/tate/proprietary/bin/atmel_touch.sh:system/bin/atmel_touch.sh \
    vendor/amazon/tate/proprietary/bin/start_smc.sh:system/bin/start_smc.sh \
    vendor/amazon/tate/proprietary/lib/hw/sensors.omap4.so:system/lib/hw/sensors.omap4.so \
    vendor/amazon/tate/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/amazon/tate/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/amazon/tate/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/amazon/tate/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
    vendor/amazon/tate/proprietary/vendor/firmware/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/amazon/jem/proprietary/vendor/etc/smc_normal_world_android_cfg.ini:system/vendor/etc/smc_normal_world_android_cfg.ini \
    vendor/amazon/tate/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/amazon/tate/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/amazon/tate/proprietary/vendor/firmware/fw_bcmdhd_p2p.bin:system/vendor/firmware/fw_bcmdhd_p2p.bin \
    vendor/amazon/tate/proprietary/vendor/firmware/maxtouch.cfg:system/vendor/firmware/maxtouch.cfg \
    vendor/amazon/tate/proprietary/vendor/firmware/maxtouch.fw:system/vendor/firmware/maxtouch.fw \
    vendor/amazon/tate/proprietary/vendor/firmware/mxt-fw20.enc:system/vendor/firmware/mxt-fw20.enc \
    vendor/amazon/tate/proprietary/vendor/firmware/smc_pa.ift:system/vendor/firmware/smc_pa.ift \
    vendor/amazon/tate/proprietary/vendor/firmware/smc_pa.ift.version:system/vendor/firmware/smc_pa.ift.version \

