# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/omap4-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/omap4-common/proprietary/vendor/lib/hw/gralloc.omap4470.so:/system/vendor/lib/hw/gralloc.omap4470.so \
    vendor/amazon/omap4-common/proprietary/vendor/lib/hw/gralloc.omap4460.so:/system/vendor/lib/hw/gralloc.omap4460.so \
    vendor/amazon/omap4-common/proprietary/vendor/lib/hw/gralloc.omap4430.so:/system/vendor/lib/hw/gralloc.omap4430.so \
    vendor/amazon/omap4-common/proprietary/etc/powervr.ini:/system/etc/powervr.ini \
    vendor/amazon/omap4-common/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/amazon/omap4-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/amazon/omap4-common/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/amazon/omap4-common/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/amazon/omap4-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/amazon/omap4-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
